dongukk/ProjectOGO

OGO/src/main/java/com/controller/notice/Create_NoticeServlet.java, OGO/src/main/java/com/controller/notice/Delete_NoticeServlet.java, OGO/src/main/java/com/controller/notice/NoticeContentServlet.java, OGO/src/main/java/com/controller/notice/Update_NoticeServlet.java, OGO/src/main/webapp/NoticeMains/NoticeTable.jsp, OGO/src/main/webapp/common/NavBar.html, OGO/src/main/webapp/notice_Content/NContent.jsp
member테이블에 정보가 없는 비회원도 공지사항을 읽을 수 있게 수정, noticeMain을 통해 억지로 로그인 하는 과정 수정
=> 공지사항 비회원 처리

OGO/src/main/webapp/MainForm.jsp
=> lofin first commit

OGO/src/main/webapp/MainForm.jsp
=> login merge test end

OGO/src/main/java/com/controller/login/MemberAddServlet.java, OGO/src/main/webapp/LoginMain/MainTest.jsp, OGO/src/main/webapp/LoginMypage/index.jsp
프로젝트 이름 변경시 파일업로드 불러오는곳 주소변경바람(현재 ogo)
=> 프로젝트 이름 변경시 파일업로드 주소 변경해주세요 (현재 주소 ogo)

OGO/src/main/webapp/sql/class_sql/classOrder.sql
classOrder 테이블 오라클db에 추가했습니다. sql문 class폴더에 넣어놨습니다.
=> classOrder 테이블 오라클db에 추가했습니다. sql문 class폴더에 넣어놨습니다.

OGO/src/main/webapp/sql/class_sql/classOrder.sql
ImdeukCho classOrder 테이블 오라클db에 추가했습니다. sql문 class폴더에 넣어놨습니다.(커밋추가)
=> ImdeukCho classOrder 테이블 오라클db에 추가했습니다. sql문 class폴더에 넣어놨습니다.(커밋추가)

OGO/src/main/webapp/LoginCURD/createMember.jsp
=> 회원가입 이용약관(모달창) 추가

OGO/src/main/webapp/LoginCURD/createMember.jsp
=> 이용 약관 css 수정

OGO/src/main/java/com/controller/classpage/ClassAddServlet.java, OGO/src/main/java/com/controller/classpage/ClassCreateServlet.java, OGO/src/main/java/com/controller/classpage/ClassPageServlet.java, OGO/src/main/webapp/ClassPage.jsp, OGO/src/main/webapp/class_css/classPage.css, OGO/src/main/webapp/class_page/box.jsp, OGO/src/main/webapp/class_page/classForm.jsp, OGO/src/main/webapp/class_page/classPhoto.jsp
=> 수강신청페이지 회차선택 기능구현,오류해결

OGO/src/main/webapp/class_css/comment.css
=> 수강후기 반응형 추가 #2

OGO/build/classes/com/config/classpage/Configuration.xml, OGO/src/main/java/com/config/classpage/Configuration.xml, OGO/src/main/webapp/HeartList/heart_01.jsp
=> Revert "mypage 수정"

OGO/src/main/java/com/controller/login/naverLogin.java, OGO/src/main/webapp/LoginCURD/naverCollback.jsp, OGO/src/main/webapp/common/LoginBar.jsp
=> 네이버 로그인 로그아웃처리 완료

OGO/src/main/webapp/LoginCURD/naverCollback.jsp, OGO/src/main/webapp/common/LoginBar.jsp
=> 네이버 로그인 버그 수정

OGO/src/main/webapp/HeartList/LoginBar.jsp, OGO/src/main/webapp/HeartList/NavBar.html, OGO/src/main/webapp/HeartList/heart_01.jsp, OGO/src/main/webapp/HeartList/index6.css, OGO/src/main/webapp/LoginMypage/index.jsp, OGO/src/main/webapp/Tutorregister/LoginBar.jsp, OGO/src/main/webapp/Tutorregister/NavBar.html, OGO/src/main/webapp/Tutorregister/indextutor.css, OGO/src/main/webapp/Tutorregister/tutor.jsp, OGO/src/main/webapp/mypageForm.jsp
=> 마이페이지 헤더 수정

OGO/src/main/webapp/LoginCURD/naverCollback.jsp, OGO/src/main/webapp/common/LoginBar.jsp
=> 로컬호스트8097 변경 - 네이버로그인 설정 변경버전

OGO/src/main/java/com/controller/login/naverLogin.java
=> 네이버로그인 회원가입 이메일저장 코드 수정

OGO/src/main/webapp/class_page/classForm.jsp
=> 클래스등록페이지 map오류해결

OGO/src/main/webapp/NoticeCURD/CreateNotice.jsp, OGO/src/main/webapp/notice_Content/NContent.jsp
=> 공지사항 제목, 내용 미입력 오류 해결

OGO/src/main/webapp/common/nav.css
=> 네비바 css 수정2

OGO/src/main/webapp/MainForm.jsp, OGO/src/main/webapp/MainForm2.jsp, OGO/src/main/webapp/mypageForm.jsp
=> 네비바 연결 css 수정

OGO/src/main/webapp/common/nav.css, OGO/src/main/webapp/common/nav.jsp
=> 네비바 그리드 시스템 적용

OGO/src/main/webapp/common/nav.css, OGO/src/main/webapp/common/nav.jsp
=> nav바 css수정

OGO/src/main/webapp/common/nav.jsp
=> nav바 css수정2

OGO/src/main/webapp/ClassList_css/style.css, OGO/src/main/webapp/ClassList_css/style1.css, OGO/src/main/webapp/ClassList_home.jsp, OGO/src/main/webapp/common/nav.css
=> 행성카테고리 css충돌 해결

OGO/src/main/webapp/common/nav.css, OGO/src/main/webapp/notice/MainNotice.jsp
=> 공지사항 네비바 css 충돌 해결

OGO/src/main/webapp/common/nav.css
=> 반응형 네비바 너비 조절2

OGO/src/main/webapp/common/nav.css, OGO/src/main/webapp/common/nav.js, OGO/src/main/webapp/common/nav.jsp
=> 네비바 메뉴버튼 애니메이션 추가

OGO/src/main/java/com/controller/login/MainFormServlet.java, OGO/src/main/webapp/ClassList_css/style1.css, OGO/src/main/webapp/ClassList_home.jsp, OGO/src/main/webapp/LoginMypage/index.jsp, OGO/src/main/webapp/LoginMypage/index4.css, OGO/src/main/webapp/MainForm.jsp, OGO/src/main/webapp/common/nav.css, OGO/src/main/webapp/common/nav.jsp, OGO/src/main/webapp/mypageForm.jsp, OGO/src/main/webapp/notice/MainNotice.jsp
MainFormServlet 추가, nav바 css겹치는거 수정, nav바 css 요청사항 변경
=> MainFormServlet 추가, nav바 css겹치는거 수정, nav바 css 요청사항 변경

OGO/src/main/webapp/common/nav.css, OGO/src/main/webapp/common/nav.jsp
=> classForm.jsp nav바 오류 수정

OGO/src/main/webapp/NoticeMains/NoticeTable.jsp, OGO/src/main/webapp/common/nav.css, OGO/src/main/webapp/common/nav.jsp
=> 공지사항 nav바 오류 수정

OGO/src/main/webapp/LoginCURD/findId.jsp, OGO/src/main/webapp/LoginCURD/findPw.jsp, OGO/src/main/webapp/LoginCURD/findPw2.jsp
id/pw찾기 이벤트 추가 (null, 이메일@미포함, 비번불일치 -> 이벤트 중지)
=> id/pw찾기 이벤트 추가 (null, 이메일@미포함, 비번불일치 -> 이벤트 중지)
